# -*- coding: utf-8 -*-
"""straightlinefit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OEcpMmDg3-4y0N13YBAC1FRKW9Qrdvav
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit


data=np.loadtxt('data.txt')
x=data[:,0]
y=data[:,1]

def f(x,slope, intercept):
    return x*slope+intercept

fparameters, covmtrx =  curve_fit(f,x,y)
m=fparameters[0]
c=fparameters[1]

plt.plot(x,y,'o',color='blue')
plt.plot(x,m*np.array(x)+c,'-', color='red')
plt.show()